version: 0.2
phases:
  install:
    commands:
      - yarn --frozen-lockfile
  pre_build:
    commands:
      - yarn --frozen-lockfile --production
  build:
    commands:
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
